### ISSUE TITLE
Be more explicit regarding the format of the file to be imported in the empty state

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/manageiq-v2v#385]
Re: comments in #379 
> Import a file including a list of VMs to be migrated

Can we be more explicit regarding the format of the file?  CSV, etc ?

**Comment by mturley** [comment]
Yeah @serenamarie125 , I think I asked at one point when nobody was listening, and I ended up just going with that text from the mockup. I would be cool with something like:

> Import a CSV file with VMs to be migrated (i)

and then when you hover/click the (i) info icon, a little popover maybe that describes the format/columns required?

Maybe not an info icon at the end, it could instead be a hover over the words "CSV file", I see dotted underlines with hover info tips occasionally.

**Comment by mturley** [comment]
or maybe

> Import a list of VMs to be migrated in CSV format (i)

**Comment by serenamarie125** [comment]
I’ve actually requested our content strategist to do a text review of all our screens :)   Waiting to hear back on her availability

**Comment by mturley** [comment]
Cool!

**Comment by mturley** [comment]
@serenamarie125 Another thing that might be useful, when you have a CSV import option, is to have an example CSV they can download as a template. Even if it's just an empty sheet with header row only, they can drop their info into it and upload. They had that on minted.com when i did my wedding guest address CSV

**Comment by vconzola** [comment]
@mturley I talked about the template idea with Brett and Marco a while ago and they liked the idea. It's just a matter of getting it prioritized, I think. Wrt having a popover describing the the format of the CSV file, I didn't think Patternfly was down with field level help, but I might be wrong. @serenamarie125 can verify I'm sure. Also, just FYI, v2v finally has a writer, so if Stacy doesn't have time to do a UI review perhaps we can run specific questions past the writer.

**Comment by mturley** [comment]
@vconzola looping back on this, since it's low priority but I didn't want to lose track of it. I think the problem with field level help for the file format is, that might be a bit of a small space to effectively describe in enough detail what is needed. It would have to be something like "A CSV file with columns for x, y z", but that doesn't explain if there needs to be a header row, or whether the delimiters matter, etc.

I think a modal that pops up a simple example of the CSV you should create, and offers to let you download an empty one with header rows or something, would be perfect here.

This would be a perfect task for a writer: how can we explain what format to make the uploaded CSV file without it being confusing and convoluted?  Maybe just the example/template file should speak for itself instead?

**Comment by vconzola** [comment]
@mturley I don't want to put examples in the UI that would require a code change if the format changes. i prefer to put a reference to the documentation where this can be spelled out in detail.
