### ISSUE TITLE
RFE - ability to edit an existing migration plan to prevent orphaning

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/manageiq-v2v#482]
To prevent orphaning a migration plan, I would like the ability to edit the plan to select a new infrastructure mapping.  Today if an infrastructure mapping is deleted that is associated to a migration plan the plan will become orphaned.

**Comment by bthurber** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1599868

**Comment by vconzola** [comment]
This has been fixed by https://github.com/ManageIQ/manageiq-v2v/pull/620 and https://github.com/ManageIQ/manageiq-v2v/pull/674.

**Comment by vconzola** [comment]
@bthurber When we edit a plan we don't allow the user change the selected infra mapping because that would necessarily change all inputs in all succeeding steps in the wizard. Therefore, it's just as easy for the user to delete the plan and create a new one and it reduces the complexity of the code for editing plans on our side. If you agree this is OK, please close this issue.

**Comment by bthurber** [comment]
Ack.
