### ISSUE TITLE
Filters on Migration Not Started Details Page

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#581]
We are seeing some spacing issues with the toolbar in FireFox.  Also, the question has been raised as to whether or not the value added by filtering/sorting functionality is worth having the additional UI element (on this particular page).

# Screens
![screenshot-from-2018-08-17-17-56-22](https://user-images.githubusercontent.com/15141412/44276866-da490980-a216-11e8-936d-78b37f802dfe.png)

**Comment by vconzola** [comment]
@michaelkro Filtering/sorting doesn't provide as much value for Not Started plans because the only field you can filter/sort on is Name and in the example above when there are only two VMs in the plan. However, it becomes alot more useful for plans with lots of VMs or for In Progress plans where the user can sort/filter to see plans by status, elapsed time, etc.

I'd like to keep it as is, even if the spacing is a little funky in Firefox. I don't think it will give anyone too much heartburn.

**Comment by michaelkro** [comment]
This issue has become stale, so closing.  Will re-open if concerns are raised again in the future
