### ISSUE TITLE
[Mapping Wizard] Only show available target providers in dropdown

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#797]
# Request for Enhancement
On the general step of the Mapping Wizard, restrict the target provider dropdown to show only providers that have been configured.  e.g., if an appliance is not configured with a RHV provider, it should not appear in the dropdown as an option

**Comment by mturley** [comment]
@mzazrivec, we accomplished this in the ConversionHostsWizard with this filter: https://github.com/ManageIQ/manageiq-v2v/blob/master/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/ConversionHostWizardLocationStep.js#L31

We should be able to just pull `providers` from state in `mapStateToProps` like we do in that wizard step: https://github.com/ManageIQ/manageiq-v2v/blob/master/app/javascript/react/screens/App/Settings/screens/ConversionHostsSettings/components/ConversionHostWizard/ConversionHostWizardLocationStep/index.js#L11 . I think it's safe to assume we already have providers in the store when the wizard opens, since we fetch providers when we mount the `Mappings` page component, so we don't need to fetch them again.

**Comment by mzazrivec** [comment]
https://github.com/ManageIQ/manageiq-v2v/pull/966
