### ISSUE TITLE
"Information" button on Migration Settings page points to broken link 

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/manageiq-v2v#801]
https://bugzilla.redhat.com/show_bug.cgi?id=1651402

**Comment by bthurber** [comment]
@vconzola FYI

**Comment by bthurber** [comment]
@vconzola any updates on this?

**Comment by vconzola** [comment]
@bthurber After discussing with Steve and Avital we concluded that trying to link to the docs directly from the UI is a bad idea because doc organization changes so often. So we're just going to remove the info button link from the UI.

@mturley Please confirm that this is done and we can close this issue and BZ.

**Comment by mturley** [comment]
@bthurber @vconzola yes, this info button was removed as part of #813. I'll close this out.
