### ISSUE TITLE
[MIGRATION TASKS] Elapsed time showing negative numbers

### ISSUE THREAD

**Issue by michaelkro** [ManageIQ/manageiq-v2v#850]
While recording a demo, it was noticed that the migration tasks were displaying a negative elapsed time.

<img width="633" alt="screencast_15-01-2019_07_58_14_webm" src="https://user-images.githubusercontent.com/15141412/51342100-f6203800-1a60-11e9-8b61-9e149a33cf46.png">

In this case, it was determined that it was caused by a difference between the system times on the server and client.

We'd like to keep an eye on this, and if it becomes a recurring problem, explore ways to prevent it

**Comment by mturley** [comment]
This is happening again on an appliance James Labocki has provisioned. I determined that it happens when the appliance clock does not agree with the browser's clock (regardless of timezone-- the ISO times don't match). We should consider a workaround where the browser checks the server's clock and offsets its own time calculations by the difference, but this would mean that scheduling a migration could result in a migration starting at the "wrong" time, so maybe we should warn the user when they go to schedule that their appliance's clock is wrong.

**Comment by mturley** [comment]
According to @fdupont-redhat we shouldn't fix this, a customer should be expected to run NTP on their appliance and have their clock in sync.
