### ISSUE TITLE
Update scheduling modal for warm migrations 

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#956]
Add additional controls for setting:
1. Refresh interval for data copies
2. Start of cutover window
3. End of cutover window

**Comment by mturley** [comment]
Note for whoever works on this: here is where we make the API call to schedule a migration today:

https://github.com/ManageIQ/manageiq-v2v/blob/master/app/javascript/react/screens/App/Overview/OverviewActions.js#L200

Note that we use `action: 'order'` with the param `resource.schedule_time` to initially schedule, and `action: 'edit'` with the param `resource.run_at.start_time` to edit the schedule. We'll need two more timestamps in each of those, and editing the schedule might be tricky because the `/api/service_templates/:planId/schedules/:scheduleId` API seems to be set up for a single specific start time, so my guess is we might have to get multiple `scheduleId`s and edit them each individually, or something like that. This is a discussion we need to have at an API/UI sync meeting.

**Comment by vconzola** [comment]
Done.
