### ISSUE TITLE
[BZ#1677677] Enhance error reporting for empty clusters

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-v2v#992]
Issue for tracking resolution of BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1752568

Description of problem:

1. Enhance error reporting for empty clusters - If your cluster is empty then it should tell in datastore that no 'datastore is present' instead of 'All source datastores have been mapped' (first video) . - NEEDS DESIGN

**Comment by mturley** [comment]
This issue was originally opened for https://bugzilla.redhat.com/show_bug.cgi?id=1677677, but the clusters selection issues part of it was duplicated as https://github.com/ManageIQ/manageiq-v2v/issues/1032 which is now associated with that original BZ. The empty clusters part was split into the new BZ https://bugzilla.redhat.com/show_bug.cgi?id=1752568, which is now associated with this issue (and I'm editing it to remove the redundant parts).
